---
metadata:
  namespace: simple-dev
  labels:
    app: simple
  name: web
apiVersion: v1
kind: Service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    role: web
  type: ClusterIP
